AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.yugabyte::spring-lambda-serverless-api
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringLambdaServerlessApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.yugabyte.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/spring-lambda-serverless-api-1.0.0-SNAPSHOT-lambda-package.zip
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 300
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringLambdaServerlessApiApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringLambdaServerlessApiApi
